name: python_scripts
channels:
  - defaults
  - conda-forge
dependencies:
  - click=7.1.2
  - jpeg=9b
  - kiwisolver
  - matplotlib=3.3.2
  - matplotlib-base
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pandas=1.2.3
  - pip=21.0.1
  - plotly=4.12.0
  - pyparsing=2.4.7
  - python=3.8.8
  - scikit-learn=0.23.2
  - scipy=1.6.1
  - sphinx=3.5.2
  - pip:
    - dictor==0.1.7
    - llvmlite==0.35.0
    - numba==0.52.0
    - nbsphinx==0.8.2
    - sphinx-gallery==0.8.2
    - pynndescent==0.5.2
    - umap-learn==0.5.1

